[package]
name = "rust-rogue"
version = "0.0.1"
edition = "2018"
authors = ["kgladfelder"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rltk = { version = "0.8.1" }
specs = "0.17.0"
specs-derive = "0.4.1"